default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

production:
  <<: *default
  database: heroku_d8c7cee09d8e486
  host: us-cdbr-east-05.cleardb.net
  username: b05cfb0c59fbca
  password: password

development:
  <<: *default
  database: myapp_development
  host: db
  username: root
  password: password

test:
  <<: *default
  database: myapp_test
  host: db
  username: root
  password: password